# Generated by Django 6.0.1 on 2026-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='tipo_rol',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('APROBADOR', 'Aprobador Administrativo'), ('GESTIONADOR', 'Gestionador de Servicios'), ('ADMINISTRADOR', 'Administrador del Sistema')], default='USUARIO', max_length=20),
        ),
    ]
