# Generated by Django 6.0.1 on 2026-01-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0003_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='viaticos.empresa'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre_rol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('empresa', 'nombre_rol')},
        ),
    ]
