# Generated by Django 6.0.1 on 2026-01-15 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0007_userprofile_actualizadopor_userprofile_creadopor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_valor', models.DateField(help_text='Fecha a la que corresponde esta tasa', unique=True)),
                ('tasa_dolar', models.DecimalField(decimal_places=4, help_text='Valor del dólar en bolívares', max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_valor'],
            },
        ),
    ]
