# Generated by Django 6.0.1 on 2026-01-15 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0008_tasacambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la localidad (Ciudad/Estado)', max_length=255, unique=True)),
                ('zona', models.CharField(help_text='Zona o región geográfica', max_length=100)),
                ('es_premium', models.BooleanField(default=False, help_text='Indica si aplica tarifa especial Premium')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
    ]
