# Generated by Django 6.0.1 on 2026-01-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0009_localidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(help_text='Ej: Alimentación, Transporte, Alojamiento...', max_length=100, unique=True)),
                ('es_premium', models.BooleanField(default=False, help_text='Indica si aplica para tarifa Premium')),
                ('montodolares', models.DecimalField(decimal_places=2, help_text='Monto base en USD', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_viaticos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_viaticos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Viático',
                'verbose_name_plural': 'Tipos de Viáticos',
                'ordering': ['tipo_gasto'],
            },
        ),
    ]
