# Generated by Django 6.0.1 on 2026-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0010_tipoviatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoviatico',
            name='gestionadicional',
            field=models.BooleanField(default=False, help_text='Indica si requiere gestión adicional'),
        ),
    ]
