# Generated by Django 6.0.1 on 2026-01-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0011_tipoviatico_gestionadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Banco')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre_banco'],
            },
        ),
    ]
