# Generated by Django 6.0.1 on 2026-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0012_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='codigo_bco',
            field=models.CharField(default='0000', help_text='Ej: 0102, 0105...', max_length=10, unique=True, verbose_name='Código del Banco'),
            preserve_default=False,
        ),
    ]
