# Generated by Django 6.0.1 on 2026-01-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0013_banco_codigo_bco'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Telefono_pagomovil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Pago Móvil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_bancarios', to='viaticos.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cedula_identidad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nro_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cuenta'),
        ),
    ]
