# Generated by Django 6.0.1 on 2026-01-15 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0014_userprofile_telefono_pagomovil_userprofile_banco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('nro_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(choices=[('NUEVO', 'Nuevo'), ('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_GESTION', 'En Gestión'), ('COMPLETADO', 'Completado'), ('RELACIONADO', 'Relacionado')], default='NUEVO', max_length=20)),
                ('cantidad_personas', models.PositiveIntegerField(default=1)),
                ('total_dolares', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_bolivares', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('aprobador_administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_por_aprobar', to=settings.AUTH_USER_MODEL)),
                ('creadopor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-nro_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('monto_dolares', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='viaticos.solicitud')),
                ('tipo_viatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaticos.tipoviatico')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
            },
        ),
    ]
