# Generated by Django 6.0.1 on 2026-01-15 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0015_solicitud_solicituddetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
