# Generated by Django 6.0.1 on 2026-01-15 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0016_alter_solicitud_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='desde',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='hasta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
