# Generated by Django 6.0.1 on 2026-01-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0017_solicitud_descripcion_solicitud_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_localidad', to='viaticos.localidad'),
        ),
    ]
