# Generated by Django 6.0.1 on 2026-01-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0018_solicitud_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo de la Empresa'),
        ),
    ]
