# Generated by Django 6.0.1 on 2026-01-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0019_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_empresa', to='viaticos.empresa'),
        ),
    ]
