# Generated by Django 6.0.1 on 2026-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0020_solicitud_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto del Usuario'),
        ),
    ]
